### ISSUE TITLE
pre-commit crashes because it is looking to C:\python36\python.exe

### ISSUE THREAD

**Issue by karlvonbonin** [conda-forge/pre_commit-feedstock#20] opened 2019-01-07 14:55 UTC
[INFO] Initializing environment for https://github.com/ambv/black.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git@ssh.git.tech.rz.db.de:iot-integration/pre-commit-isort.git.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/ambv/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('C:\\Miniconda3\\envs\\test-project\\python.exe', '-mvirtualenv', 'C:\\Users\\myuser\\.cache\\pre-commit\\repot5wgp278\\py_env-python3.6', '-p', 'C:\\python36\\python.exe')
Return code: 3
Expected return code: 0
Output:
    The path C:\python36\python.exe (from --python=C:\python36\python.exe) does not exist

Errors: (none)

Iam still getting this issue - it seems that pre-commit looks to a different python version ?

**Comment by nicoddemus** [comment] 2019-01-07 15:36
Is this an issue with the package or a `pre-commit` problem? If the later, we should open an issue in the `pre-commit` repository.

**Comment by asottile** [comment] 2019-01-10 17:56
I believe this is a dupe of https://github.com/pre-commit/pre-commit/issues/913 and will be fixed in 1.14.1

**Comment by asottile** [comment] 2019-01-11 20:31
this should be resolved now that 1.14.1 and 1.14.2 has been released

**Closed as completed** 2019-01-11 20:43 UTC
